/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author dorron
 */
import BL.Klienti;
import DAL.KlientiRepository;
import DAL.KlientiException;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class RegjistrimiKlientitWindow extends javax.swing.JInternalFrame {

    /** Creates new form RegjistrimiKlientitWindow */
    public RegjistrimiKlientitWindow() {
        initComponents();
        this.setTitle("Regjistrimi i klientit");
    }
    /** Objektet E instacuara */
    KlientiRepository kR = new KlientiRepository();
    Klienti klient;
    
    public RegjistrimiKlientitWindow(Klienti k){
        initComponents();
        this.setTitle("Editimi i klientit");
        klient = k;
        emriTexField.setText(k.getEmri());
        mbiemriTextField.setText(k.getMbiemri());
        if(k.getGjinija() == 'M')
            jComboBox1.setSelectedIndex(1);
        else
           jComboBox1.setSelectedIndex(1);
        shtetiTextField.setText(k.getShteti());
        qytetiTextField.setText(k.getQyteti());
        rrugaTextField.setText(k.getRruga());
        ditelindjaDateChoose.setDate(k.getDitelindja());
        kodiPostarTextField.setText(k.getKodiPostar()+"");
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emriTexField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mbiemriTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ditelindjaDateChoose = new com.toedter.calendar.JDateChooser();
        Gjinija = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        shtetiTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qytetiTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rrugaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kodiPostarTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setTitle("Regjistro / Edito Klientin");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Të dhënat kryesore"));
        jPanel1.setToolTipText("");

        jLabel1.setText("Emri:");

        jLabel2.setText("Mbiemri:");

        jLabel4.setText("Ditëlindja:");

        Gjinija.setText("Gjinija:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zgjidh","M","F"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mbiemriTextField)
                            .addComponent(ditelindjaDateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(emriTexField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Gjinija, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emriTexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ditelindjaDateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Gjinija)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresa"));

        jLabel6.setText("Shteti:");

        jLabel7.setText("Qyteti:");

        jLabel8.setText("Rruga:");

        jLabel9.setText("Kodi Postar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qytetiTextField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rrugaTextField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shtetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kodiPostarTextField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(shtetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(qytetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rrugaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kodiPostarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Ruaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**  Kjo metode ben regjstrimin e klientit */    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
           Date dL = ditelindjaDateChoose.getDate();
           String emri = emriTexField.getText();
           String mbiemri = mbiemriTextField.getText();
           String gj = (String) jComboBox1.getSelectedItem();
           char gjinija = gj.charAt(0);
           String shteti = shtetiTextField.getText();
           String qyteti = qytetiTextField.getText();
           String rruga = rrugaTextField.getText();
          

           if (jComboBox1.getSelectedIndex() < 1 && emriTexField.getText().equals("") || emriTexField == null && mbiemriTextField.getText().equals("") || mbiemriTextField == null && ditelindjaDateChoose.getDate() == null && shtetiTextField.getText().equals("") || shtetiTextField == null && rrugaTextField.getText().equals("") || rrugaTextField == null && kodiPostarTextField.getText().equals("") || kodiPostarTextField == null) {
               JOptionPane.showMessageDialog(this, "Nuk e keni mbushur asnjë opsion!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (jComboBox1.getSelectedIndex() < 1) {
               JOptionPane.showMessageDialog(this, "Nuk e keni zgjedhur gjininë!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (emriTexField.getText().equals("") || emriTexField == null) {
               JOptionPane.showMessageDialog(this, "Nuk e keni shkruar emrin!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (mbiemriTextField.getText().equals("") || mbiemriTextField == null) {
               JOptionPane.showMessageDialog(this, "Nuk e keni shtypur mbiemrin!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (ditelindjaDateChoose.getDate() == null) {
               JOptionPane.showMessageDialog(this, "Nuk keni shkruar ditëlindjen!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (shtetiTextField.getText().equals("") || shtetiTextField == null) {
               JOptionPane.showMessageDialog(this, "Nuk keni shkruar shtetin!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (rrugaTextField.getText().equals("") || rrugaTextField == null) {
               JOptionPane.showMessageDialog(this, "Nuk e keni shkruar rrugën!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           } else if (kodiPostarTextField.getText().equals("") || kodiPostarTextField == null) {
               JOptionPane.showMessageDialog(this, "Nuk e keni shkruar Kodin postar!", "Gabim!", JOptionPane.ERROR_MESSAGE);
           }else{
              if(klient != null){
                  int kodiPostar = Integer.parseInt(kodiPostarTextField.getText());
                  
                  klient.setEmri(emri);
                  klient.setGjinija(gjinija);
                  klient.setMbiemri(mbiemri);
                  klient.setShteti(shteti);
                  klient.setDitelindja(dL);
                  klient.setQyteti(qyteti);
                  klient.setRruga(rruga);
                  klient.setKodiPostar(kodiPostar);
                  kR.edit(klient);
                  JOptionPane.showMessageDialog(this, "Klienti u editua");  
              }else if (klient == null){
                  int kodiPostar = Integer.parseInt(kodiPostarTextField.getText());
                  Klienti kk = new Klienti();
                  kk.setEmri(emri);
                  kk.setGjinija(gjinija);
                  kk.setMbiemri(mbiemri);
                  kk.setShteti(shteti);
                  kk.setDitelindja(dL);
                  kk.setQyteti(qyteti);
                  kk.setRruga(rruga);
                  kk.setKodiPostar(kodiPostar);
                  kR.create(kk);
                  JOptionPane.showMessageDialog(this, "Klienti u ruajt");
              }
           }
          
           
       }catch(KlientiException kE){
            JOptionPane.showMessageDialog(this, kE.getMessage(), "Gabim!", JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gjinija;
    private com.toedter.calendar.JDateChooser ditelindjaDateChoose;
    private javax.swing.JTextField emriTexField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kodiPostarTextField;
    private javax.swing.JTextField mbiemriTextField;
    private javax.swing.JTextField qytetiTextField;
    private javax.swing.JTextField rrugaTextField;
    private javax.swing.JTextField shtetiTextField;
    // End of variables declaration//GEN-END:variables

}
