 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Klienti;
import DAL.KlientiRepository;
import BL.KontaktiKlienti;
import DAL.KontaktiKlientiRepository;
import DAL.KlientiException;
import DAL.KontaktiKlientiException;
import java.util.List;
import javax.swing.JList;
import java.util.Iterator;
import javax.swing.JOptionPane;


      

/**
 *
 * @author dorron
 */
public class RegjistrimiIKontaktitKlienititWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegjistrimiIKontaktitKlienititWindow
     */
    public RegjistrimiIKontaktitKlienititWindow() {
        initComponents();
    }
    /** Objektet E instacuara */
    
    KontaktiKlientiRepository kkR = new KontaktiKlientiRepository();
    KlientiRepository kR = new KlientiRepository();
    
    public Klienti[] convertToArray(){
       int i = 0;
       List<Klienti> l = kR.findAll();
       Iterator<Klienti> li = l.iterator();
       Klienti[] list = new Klienti[l.size()];
       while(li.hasNext()){
           if(i < l.size())
               list[i++] = li.next();
       }
       return list;
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        KlientiPanel = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nrTelTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setTitle("Regjistrimi / Editimi i kontaktit të klientit");

        KlientiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selekto Klientin"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(convertToArray()));

        javax.swing.GroupLayout KlientiPanelLayout = new javax.swing.GroupLayout(KlientiPanel);
        KlientiPanel.setLayout(KlientiPanelLayout);
        KlientiPanelLayout.setHorizontalGroup(
            KlientiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KlientiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        KlientiPanelLayout.setVerticalGroup(
            KlientiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KlientiPanelLayout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kontaktet"));

        jLabel1.setText("Telefoni:");

        jLabel2.setText("Email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nrTelTextField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(emailTextField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nrTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setText("Ruaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(KlientiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(KlientiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if(emailTextField.getText().equals("") || emailTextField == null && nrTelTextField.getText().equals("") || nrTelTextField == null && jComboBox2.getSelectedIndex() < 0)
                 JOptionPane.showMessageDialog(this, "Asnjë nga opcionet si keni mbushur!","Gabim!",JOptionPane.ERROR_MESSAGE);
            else if(jComboBox2.getSelectedIndex() < 0)
                 JOptionPane.showMessageDialog(this, "Nuk e keni zgjedhur klientin!","Gabim!",JOptionPane.ERROR_MESSAGE);
            else if(emailTextField.getText().equals("") || emailTextField == null)
                 JOptionPane.showMessageDialog(this, "Nuk e keni shtypur email!","Gabim!",JOptionPane.ERROR_MESSAGE);
            else if(nrTelTextField.getText().equals("") || nrTelTextField == null)
                JOptionPane.showMessageDialog(this, "Nuk e keni shtypur numrin e telefonit!","Gabim!",JOptionPane.ERROR_MESSAGE);
            else{
                KontaktiKlienti kk = new KontaktiKlienti();
                kk.setTel(nrTelTextField.getText());
                kk.setEmail(emailTextField.getText());
                Klienti k = (Klienti)jComboBox2.getSelectedItem();
                kk.setIDKlienti(k);
                kkR.create(kk);
                JOptionPane.showMessageDialog(this, "U regjistrua me sukses!");
            }
        }catch(KontaktiKlientiException ke){
            JOptionPane.showMessageDialog(this, ke.getMessage(),"Gabim!",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KlientiPanel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Klienti> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nrTelTextField;
    // End of variables declaration//GEN-END:variables
}
